version: '3'
services:
  pig-ui:
    build:
      context: .
    restart: always
    container_name: pig-ui
    image: pig-ui
    networks:
      - pig367_default
    external_links:
      - pig-gateway
    ports:
      - 80:80

# 加入到后端网络， 默认为 pig_default  | docker network ls   查看
networks:
  pig367_default:
    external: true